import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next'
import type { TImages } from '../types/Images'
import Head from 'next/head'
import Header from '../components/common/Header'
import HomeContainer from '../components/home/Container'

type HomeProps = {
  images: TImages[]
}

const Home: NextPage = ({
  images,
}: HomeProps | InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <main>
      <Head>
        <title>Next Galleria | by mrLuisFer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeContainer images={images} />
    </main>
  )
}
export default Home

export const getStaticProps: GetStaticProps = async (context) => {
  const res: Response = await fetch('https://picsum.photos/v2/list')
  const imagesData: TImages[] = await res.json()

  return {
    props: {
      images: imagesData,
    },
  }
}
