import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/common/Header'
import HomeContent from '../components/home/Content'
import type {TImages} from '../types/Images'

const Home: NextPage = ({images}: InferGetStaticPropsType<typeof getStaticProps>) => {

  return (
    <main className={styles.container}>
    	<Head>
        <title>Next Galleria | by mrLuisFer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Header />
			<HomeContent images={images} />
		</main>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async (context) => {
	const res: Response = await fetch('https://picsum.photos/v2/list')
	const imagesData: TImages[] = await res.json()

	return {
		props: {
			images: imagesData,
		},
	}
}


